[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "xplorts"
version = "0.1"
authors = [
  { name="Todd M Bailey", email="shoppert@baileywick.plus.com" },
]
description = "Make standalone interactive HTML charts to explore time series datasets"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
#"Homepage" = "https://github.com/pypa/sampleproject"
#"Bug Tracker" = "https://github.com/pypa/sampleproject/issues"
